KobithaBoli.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace KobithaBoli.MVC.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

     
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Poem()
        {
            ViewBag.Message = "Your Poetry page.";

            return View();
        }
   

    }
}

KobithaBoli.MVC/Controllers/PoemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace KobithaBoli.MVC.Controllers
{
    public class PoemController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();

        }

    }
}

KobithaBoli.MVC/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace KobithaBoli.MVC.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

KobithaBoli.MVC/Views/Home/About.Mobile.cshtml
@{
    ViewBag.Title = "About.Mobile";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}



<script>

    $(document).bind("pagebeforeshow", function (e, data) {
      
    var $footers = $(document).find('div[data-role="footer"]');
    $footers.find('a').removeClass("ui-btn-active");
    $footers.find('a[data-name="about"]').addClass("ui-btn-active");

});



</script>

KobithaBoli.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>About</h2>

KobithaBoli.MVC/Views/Home/Contact.Mobile.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}
<form id="contactus" action="Home/ContactUs" method="post">
<div data-role="fieldcontainer">
<label for="company">Name:</label>
<input type="text" id="company" required name="company" placeholder="Name">
</div>
<div data-role="fieldcontainer">
<label for="email">Email:</label>
<input type="email" id="email" required name="email" placeholder="Email">
</div>
    <input type="submit" data-theme="b" value="Submit" data-role="button">
   
    </form>

<script>

    $(document).bind("pagebeforeshow", function (e, data) {
     
    var $footers = $(document).find('div[data-role="footer"]');
    $footers.find('a').removeClass("ui-btn-active");
    $footers.find('a[data-name="contact"]').addClass("ui-btn-active");

});



</script>

KobithaBoli.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div data-role="fieldcontainer">
<label for="company">Company Name:</label>
<input type="text" id="company" name="company">
</div>
<div data-role="fieldcontainer">
<label for="email">Email:</label>
<input type="email" id="email" name="email">
</div>
<div data-role="fieldcontainer">
<label for="comments">Your comments:</label>
<textarea id="comments" name="comments></textarea>
</div>

KobithaBoli.MVC/Views/Home/Index.Mobile.cshtml
@{
    ViewBag.Title = "Index.Mobile";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}

<div data-theme="b" data-role="collapsible">
<h2>History of Rome</h2>
<p>There is archaeological evidence of human occupation of the Rome area from at
least 14,000 years, but the dense layer of much younger debris obscures
Palaeolithic and Neolithic sites.[11] Evidence of stone tools, pottery and
stone weapons attest to at least 10,000 years of human presence.
</p>
</div>
<div data-role="collapsible" data-theme="b"  data-collapsed="true">
<h2>Government of Rome</h2>
<p>Rome constitutes one of Italy's 8,101 communes, and is the largest both in terms
of land area and population. It is governed by a mayor, currently Gianni Alemanno,
and a city council.
</p>
</div>

KobithaBoli.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

KobithaBoli.MVC/Views/Home/Poem.Mobile.cshtml
@{
    ViewBag.Title = "Poem";
}

<ul data-role="listview" data-inset="true" data-theme="b" data-divider-theme="b">
<li><a href="@Url.Action("Detail", "Poem")" >Poem 1</a>
</li>
 
 <li><a href="@Url.Action("Detail", "Poem")" >Poem 2</a>
</li>
</ul>

<script>

    $(document).bind("pagebeforeshow", function (e, data) {
     
    var $footers = $(document).find('div[data-role="footer"]');
    $footers.find('a').removeClass("ui-btn-active");
    $footers.find('a[data-name="poem"]').addClass("ui-btn-active");

    });

    </script>

KobithaBoli.MVC/Views/Home/Poem.cshtml
@{
    ViewBag.Title = "Poem";
}

<h2>Poem</h2>

KobithaBoli.MVC/Views/Poem/Detail.Mobile.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Poem Details</h1>

<script>

    $(document).bind("pagebeforeshow", function (e, data) {
     
    var $footers = $(document).find('div[data-role="footer"]');
    $footers.find('a').removeClass("ui-btn-active");
    $footers.find('a[data-name="poem"]').addClass("ui-btn-active");

});



</script>

KobithaBoli.MVC/Views/Poem/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

KobithaBoli.MVC/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
         
             <h2>Amar Kobitha Boli</h2>    
          

        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

        <div data-role="footer"  data-position="fixed">
            <div data-role="navbar">
            <ul>
            <li><a data-name="home" href="@Url.Action("Index", "Home")" class="ui-btn-active ui-state-persist" data-icon="home">Home</a>
            <li><a data-name="poem" href="@Url.Action("Poem", "Home")" data-icon="search">Poems</a>
            <li><a data-name="about" href="@Url.Action("About", "Home")" data-icon="info">About</a>
            <li>
            <a id="contact" data-name="contact" href="@Url.Action("Contact", "Home")" style="text-align:center" data-icon="grid">Contact</a>
                            </ul>
</div>

        </div>
    </div>

</body>
</html>

KobithaBoli.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_ViewSwitcher")
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

KobithaBoli.MVC/Views/Shared/_ViewSwitcher.cshtml
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>